### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 0u44** [0x61nas/pinterest-login#115]
**Is your feature request related to a problem? Please describe.**
> NO, Just bored <3

- Sigma Sigma

**Describe the solution you'd like**
- On the wall

**Describe alternatives you've considered**
- Whos the skibidi'st

**Additional context**
- Of them all!

# (PS: ITS YOU)

**Comment by 0u44** [comment]
FEATURE REQUEST 115!?!?!?!?  **WHAT**

**Comment by 0x61nas** [comment]
what??

**Comment by 0u44** [comment]
your sigma
